FROM php:7.4.5-fpm-alpine

MAINTAINER leeprince@foxmail.com

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories \
    && apk add \
        autoconf g++ make \
        git \
        openssl-dev

RUN mv "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini" \
    && docker-php-ext-install \
        mysqli \
        pdo_mysql \
        sockets \
    && pecl install redis && docker-php-ext-enable redis \
    && pecl install swoole && docker-php-ext-enable swoole

# Composer
RUN curl -sS https://getcomposer.org/installer | php \
    && mv composer.phar /usr/local/bin/composer \
    && composer self-update --clean-backups

# 全局配置 composer 镜像地址
RUN composer config -g repo.packagist composer https://mirrors.aliyun.com/composer/

# $PHP_INI_DIR = /usr/local/etc/php
VOLUME ["/var/www/html"]

COPY ./conf/php.ini /usr/local/etc/php/php.ini

EXPOSE 9000

WORKDIR /var/www/html

